### PR TITLE
Add difficulty + overall parameters

### PR DESCRIPTION
**Pull request by kewbish**
This PR passes the difficulty + overall course quality parameters to the GitHub issues creation API. 

Also fixes the user reference - we want to use `<cite>` and not just a link. As well, added the current date as per ubccsss/ubccsss.org#212.

I clamp this to 1-5 and check for the JSON type. This should already be safely ensured in the UI, but if someone hits our worker with a script somehow having already passed the Captcha I figured we may as well add some verification to be safe.

### CODE REVIEW

**Review by AnimeAllstar — COMMENTED** [review]
Are we doing validation checks for type in the frontend? Also, you could use`isNaN` to check the type.

**Comment by kewbish** [comment]
We're sending the input value as a range, so it should only be a float in the specified range. Felt that it might be good to add more validation on the worker side, unless you feel the UI-side should be enough. No strong opinions :shrug:

**Comment by AnimeAllstar** [comment]
> We're sending the input value as a range, so it should only be a float in the specified range. Felt that it might be good to add more validation on the worker side, unless you feel the UI-side should be enough. No strong opinions 🤷

I don't think we should add any validation on the worker side honestly. All the validation should be done client side. If we expect a float, there's no need to check again.

**Comment by AnimeAllstar** [comment]
test

**Comment by AnimeAllstar** [comment]
hello

**Comment by AnimeAllstar** [comment]
test 2

**Comment by AnimeAllstar** [comment]
test 3

**Review by AnimeAllstar — APPROVED** [review]

**Comment by kewbish** [comment]
@AnimeAllstar Could you re-deploy on Cloudflare please (doesn't look like it automatically is)? Just want to make sure this is deployed before I merge the theme changes :pray:

**Comment by AnimeAllstar** [comment]
@kewbish done. You just have to run:

```
$ wrangler publish  # publishes dev environment
$ wrangler publish --env production  # publishes production environment
```

after `wrangler login`.

The dev environment is for local testing and for deploy previews in the ubccsss.org repo.

**Comment by kewbish** [comment]
Good to know! I don't think I have the creds for `wrangler login` though - IDT I'll make more changes soon but I'll ask you for creds if I need them.

**Pull request merged**
